# Generated by Django 4.2.4 on 2023-12-08 01:29

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0003_rename_student_adduser_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AddCompany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("com_name", models.CharField(max_length=100)),
                ("com_addresses", models.CharField(max_length=100)),
                ("com_phone", models.IntegerField()),
                ("com_product", models.CharField(max_length=100)),
                ("com_goods", models.CharField(max_length=100)),
                ("com_service", models.CharField(max_length=100)),
                ("com_email", models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="AppSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("app_footer", models.CharField(max_length=100)),
                ("app_signup_logo", models.ImageField(upload_to="images/")),
                ("app_favicon", models.ImageField(upload_to="images/")),
                ("app_color", chat.models.ColorField(max_length=7)),
                ("app_title", models.CharField(max_length=100)),
                ("app_adminlogo", models.ImageField(upload_to="images/")),
                ("app_loginimage", models.ImageField(upload_to="images/")),
                ("app_admintext", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="BotSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("api_key", models.CharField(max_length=200)),
                ("system_role", models.CharField(max_length=100)),
                ("bot_model", models.CharField(max_length=400)),
                ("bot_name", models.CharField(max_length=100)),
                ("bot_image", models.ImageField(upload_to="images/")),
            ],
        ),
        migrations.CreateModel(
            name="FbIntegrate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fb_pagename", models.CharField(max_length=100)),
                ("fb_pageid", models.CharField(max_length=100)),
                ("fb_appname", models.CharField(max_length=100)),
                ("fb_appid", models.CharField(max_length=100)),
                ("fb_secretkey", models.CharField(max_length=100)),
                ("fb_verifytoken", models.CharField(max_length=100)),
                ("fb_accesstoken", models.CharField(max_length=100)),
                ("fb_logo", models.ImageField(upload_to="images/")),
            ],
        ),
    ]
