# Generated by Django 4.2.4 on 2023-12-11 16:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0004_addcompany_appsetting_botsetting_fbintegrate"),
    ]

    operations = [
        migrations.AddField(
            model_name="addcompany",
            name="user_id",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="appsetting",
            name="user_id",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="botsetting",
            name="user_id",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="fbintegrate",
            name="user_id",
            field=models.IntegerField(default=1),
        ),
    ]
