# Generated by Django 4.2.4 on 2023-12-12 13:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0005_addcompany_user_id_appsetting_user_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_image",
            field=models.ImageField(default="user", upload_to="images/"),
        ),
    ]
