# Generated by Django 4.2.4 on 2023-12-12 13:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0006_user_user_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_image",
            field=models.ImageField(
                default="chat/assets/images/first-chat.png", upload_to="images/"
            ),
        ),
    ]
