# Generated by Django 4.2.4 on 2023-12-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0007_alter_user_user_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adduserprofile",
            name="student_id",
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
